server:
  port: 8080

spring:
  application:
    name: mi-dialogue

---

spring:
  profiles: dev
  redis:
    host: 192.168.0.119
server:
  port: 8081

dialogue:
  redis:
    channel: dialogue.redis.sample.channel
  rabbit:
    channel: dialogue.rabbit.sample.channel


kafka:
  broker:
    address: 192.168.0.119:9092
  zookeeper:
    connect: 192.168.0.119:2181
  topic: si.topic6
  messageKey: si.key6